### ISSUE TITLE
Update AFNI to later version

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcpd_build#4]
Currently experiencing Malloc problems with M1 , potentially combine within docker image

**Comment by tsalo** [comment]
I'm not all that familiar with Neurodebian, but it looks like the most recent version available through them is the one we have: https://neuro.debian.net/pkgs/afni.html

Can we just switch to installing it without Neurodebian?

**Comment by tsalo** [comment]
I've been looking at NeuroDocker and other installation options, but it seems like they only let us install the latest release. That doesn't seem very reproducible in the long term, if every time someone builds the Docker image, they're grabbing the newest release of AFNI. @mattcieslak WDYT?

**Comment by tsalo** [comment]
Per the discussion today, we might want to create a new report to build Docker images containing the most recent version of AFNI, tagged with the associated AFNI version. That way, we can just grab the necessary binaries from that image. It would also be useful for several projects.

**Comment by mattcieslak** [comment]
I think this has been resolved?
